In [20]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np
import requests
import time
from scipy.stats import linregress

# Import API key
from api_keys import weather_api_key
# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

In [21]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = []

# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=1500)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=1500)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

614

In [28]:
# Save config information.
url = "http://api.openweathermap.org/data/2.5/weather?"
units = "metric"

lst_City = []
lst_Lat = []
lst_Lng = []
lst_Max_Temp = []
lst_Humidity = []
lst_Cloudiness = []
lst_Wind_Speed = []
lst_Country = []
lst_Date = []


# Build partial query URL
query_url = f"{url}appid={weather_api_key}&units={units}&q="

for city in cities:
    req = requests.get(query_url + city)
    response = req.json()
    if req.status_code != 404:
        lst_City.append(response['name'])
        lst_Lat.append(response["coord"]["lat"])
        lst_Lng.append(response["coord"]["lon"])
        lst_Max_Temp.append(response["main"]["temp_max"]) 
        lst_Humidity.append(response["main"]["humidity"])
        lst_Cloudiness.append(response["clouds"]["all"])
        lst_Wind_Speed.append(response["wind"]["speed"])
        lst_Country.append(response["sys"]["country"])
        lst_Date.append(response["dt"])
        
dict_global_weather = {
    "City":lst_City, 
    "Lat": lst_Lat, 
    "Lng":lst_Lng,
    "Max Temp":lst_Max_Temp,
    "Humidity":lst_Humidity,
    "Cloudiness":lst_Cloudiness,
    "Wind Speed":lst_Wind_Speed,
    "Cloudiness":lst_Cloudiness,
    "Wind Speed":lst_Wind_Speed,
    "Country": lst_Country,
    "Date":lst_Date
}

# Create Presentation DataFrame for Distrcit
df_global_weather = pd.DataFrame(dict_global_weather)

df_global_weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Pandan,14.0453,124.1694,28.41,71,53,5.28,PH,1635734991
1,Vysokogornyy,50.1167,139.1500,0.80,44,1,1.26,RU,1635735090
2,Carnarvon,-24.8667,113.6333,22.04,56,75,7.72,AU,1635735090
3,Chandler,33.3062,-111.8412,26.02,31,7,2.11,US,1635734916
4,Chui,-33.6971,-53.4616,17.34,98,92,2.93,UY,1635735070
...,...,...,...,...,...,...,...,...,...
559,Baruun-Urt,46.6806,113.2792,1.92,32,11,6.63,MN,1635735264
560,Norton,-17.8833,30.7000,19.60,54,15,3.20,ZW,1635735265
561,San Policarpo,12.1791,125.5072,28.27,77,58,6.75,PH,1635735265
562,Benguela,-12.5763,13.4055,22.61,80,82,1.32,AO,1635735266
563,Buguruslan,53.6554,52.4420,4.46,87,22,3.93,RU,1635735266

In [30]:
df_global_weather.to_csv('weather_output.csv')